### ISSUE TITLE
Make a link to the raw video feed for ease of use with OBS

### ISSUE THREAD

**Issue by monkeymademe** [monkeymademe/picamera2-WebUI#29]
Make a link to the raw video feed for ease of use with OBS.

Top menu item - 'Raw video feed'?

**Comment by geerlingguy** [comment]
Maybe since this is more an advanced feature, it could be on the Camera Info page, and be able to be easily selected for copy + paste.

I would like to try using the feed with VLC (for streaming to another computer), or maybe even with other apps on the Pi like Octoprint, since the Pi 5 integration for the Pi camera streaming isn't working yet.

**Comment by monkeymademe** [comment]
Added the links to copy and its been tested working with VLC, OBS and Octoprint... Enjoy!

![image](https://github.com/user-attachments/assets/f8c7d49d-44fd-422a-a4c1-f172805518b1)

**Comment by geerlingguy** [comment]
Beautiful! The only other suggestion - if you could make the links click-to-copy, like: `user-select-all`, that would make copying them out even easier (though just having the link means you can click it, then Command+L (on Mac, at least) and copy from the URL field).

**Comment by monkeymademe** [comment]
No worries

<img width="673" alt="image" src="https://github.com/user-attachments/assets/0072a90e-b79c-442f-914e-7df844cf66b9">
