### ISSUE TITLE
Add frame rate option to time lapse 

### ISSUE THREAD

**Issue by codemonkey2k5** [monkeymademe/picamera2-WebUI#37]
It would be very helpful if you could designate how many images per sec/min/hour the screen capture option takes. 
This would help for those with limited storage space.   For days long prints, 1 frame per 5 min may be enough.

**Comment by monkeymademe** [comment]
If you are talking about the timelapse feature... thats totally far from unfinished... what I put in was a quick hack for an event. This is lowish in the prio to fix.

BUT... 

If you fancy a little dig in the code in line 351 of the app.py file there is a variable `interval = 2` which is in seconds so edit that and the interval will change

**Comment by codemonkey2k5** [comment]
Yep and thanks for the insight.   Appreciate the quick response.

**Comment by monkeymademe** [comment]
I am closing this ticket because timelapse is an unfinished feature and will not be in the next major release. But will be implemented after that (1.0.0 will be pi5 support and 1.0.1,2,3 etc will be fixes 1.1.0 will be timelapse... or there abouts)

Don't worry timelapse is important and will be there
